language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - sudo apt-get install -y libevent-dev libev-dev
  - yes "" | pecl install libevent-beta
  - echo "extension=libevent.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - (git clone --recursive https://github.com/m4rw3r/php-libev && cd php-libev && phpize && ./configure && make && make install)
  - echo "extension=libev.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --dev

script: phpunit --coverage-text
