language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - sudo apt-get install -y libevent-dev libev-dev
  - yes "" | pecl install libevent-beta
  - echo "extension=libevent.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - yes "" | pecl install eio
  - echo "extension=eio.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer install --dev

script: phpunit --coverage-text
