language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - sudo apt-get install -y libevent-dev libev-dev
  - sh -c " if [ \"\$(php --re libevent | grep 'does not exist')\" != '' ]; then
              (yes '' | pecl install libevent-beta)
            fi"
  - (git clone --recursive https://github.com/m4rw3r/php-libev && cd php-libev && phpize && ./configure && make && make install)
  - echo "extension=libev.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - (git clone --recursive https://github.com/chobie/php-uv.git && cd php-uv && cd libuv && make libuv.a CFLAGS=-fPIC && cd .. && phpize && ./configure && make && make install)
  - echo "extension=uv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer install --dev --prefer-source

script: phpunit --coverage-text
