language: php

php:
  - 5.3
  - 5.4

before_script:
  - sudo apt-get install -y libevent-dev
  - yes "" | pecl install libevent-beta
  - echo "extension=libevent.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit --coverage-text
